### ISSUE TITLE
Milestone 4 wrap-up

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#36]
On 2 December we had a meeting and concluded that work left for milestone 4 was:
* [x] #32 
* [x] #33 
* [x] #34

Apart from this, we need to:
* [x] get https://github.com/nextcloud/server/pull/35555 ready for merging upstream
  * [x] sign-off
  * [x] performance
  * [x] cypress
  * [x] CI 
* [x] get https://github.com/nextcloud/user_saml/pull/668 ready for merging upstream
* [x] get https://github.com/nextcloud/globalsiteselector/pull/80 ready for merging upstream
* [x] get https://github.com/nextcloud/server/pull/36045 ready for merging upstream
  * [x] sign-off
  * [x] conflicts
  * [x] changes requested re operator / values of the check (pending: add screenshots)
  * [x] investigate failing `checkers` test
